minify: true

favicon:
  small: /favicon-16x16.png
  medium: /favicon-32x32.png
  apple_touch_icon: /apple-icon-180x180.pgn

footer:
  since: 2016
  icon:
    name: user
    animated: false
    color: "#808080"
  copyright:

disable_baidu_transformation: true

google_site_verification: aca2a971997c102c

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  about: /about.html || fa fa-user

scheme: Gemini
darkmode: true

social:
  Twitter: https://twitter.com/kemchenj || fab fa-twitter
  Telegram: https://t.me/kemchenj || fab fa-telegram
  E-Mail: mailto:chenkem@gmail.com || fas fa-envelope
  Resume: /resume.html || fa fa-address-book

links_settings:
  title: 推荐的博客
links:
  iOS 周报: https://github.com/SwiftOldDriver/iOS-Weekly
  iOS Dev Weekly: https://iosdevweekly.com
  Swift Weekly Brief: https://swiftweekly.github.io
  SwiftGG: http://swift.gg/
  喵神博客: https://onevcat.com
  Objective-C 中国: https://objccn.io/issues/

avatar:
  url: /images/avatar.jpg

toc:
  expand_all: true

back2top:
  sidebar: true

mobile_layout_economy: true

codeblock:
  prism:
    light: prism
    dark: prism-okaidia
  copy_button:
    enable: true
    style: mac

github_banner:
  enable: true
  permalink: https://github.com/kemchenj
  title: Follow me on GitHub

gitalk:
  enable: true
  github_id: kemchenj # GitHub repo owner
  repo: kemchenj.github.io # Repository name to store issues
  client_id: "ac4cd8966b518e34301a"   # GitHub Application Client ID
  client_secret: "6a8817fe329fc5c4213d860a6b713cd5496d6529"  # GitHub Application Client Secret
  admin_user: kemchenj # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  language: zh-CN

local_search:
  enable: true
  top_n_per_article: 5

motion:
  enable: false

vendors:
  internal: jsdelivr

custom_file_path:
  variable: source/_data/variables.styl
  style: source/_data/styles.styl
