minify: true

favicon:
  small: /favicon-16x16.png
  medium: /favicon-32x32.png
  apple_touch_icon: /apple-icon-180x180.png
  safari_pinned_tab: 

footer:
  since: 2016
  icon:
    name: user
    animated: false
    color: "#808080"
  copyright:

disable_baidu_transformation: true

google_site_verification: aca2a971997c102c

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  about: /about.html || fa fa-user

scheme: Gemini
darkmode: true

social:
  Twitter: https://twitter.com/kemchenj || fab fa-twitter
  RSS: https://kemchenj.github.io/atom.xml || fas fa-rss

links:
  老司机 iOS 周报: https://github.com/SwiftOldDriver/iOS-Weekly/releases
  iOS Dev Weekly: https://iosdevweekly.com
  SwiftGG: http://swift.gg/
  喵神博客: https://onevcat.com
  Objective-C 中国: https://objccn.io/issues/
  13 周报: https://www.ethanhuang13.com
  波报: https://pofat.substack.com

preconnect: true

avatar:
  url: /images/avatar.jpg

toc:
  number: false
  expand_all: true
  max_depth: 3

back2top:
  sidebar: true
  scrollpercent: true

mobile_layout_economy: true

codeblock:
  prism:
    light: prism
    dark: prism-okaidia
  copy_button:
    enable: true
    style: mac

github_banner:
  enable: true
  permalink: https://github.com/kemchenj/kemchenj.github.io
  title: Source Code

local_search:
  enable: true
  top_n_per_article: 5

motion:
  enable: false

vendors:
  internal: cdnjs
  plugins: cdnjs

custom_file_path:
  head: source/_data/head.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl
