minify: true

favicon:
  small: /avatar.jpg
  medium: /avatar.jpg
  apple_touch_icon: /avatar.jpg
  safari_pinned_tab: /avatar.jpg
  android_manifest: /avatar.jpg
  ms_browserconfig: /avatar.jpg

footer:
  since: 2016
  icon:
    name: user
    animated: false
    color: "#808080"
  copyright:

disable_baidu_transformation: true

canonical: true

seo: true

exturl: true

google_site_verification: aca2a971997c102c

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  about: /about.html || fa fa-user

scheme: Gemini
darkmode: true

# Social Links
# Usage: `Key: permalink || icon`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink.
# Value after `||` delimiter is the name of Font Awesome icon. If icon (with or without delimiter) is not specified, globe icon will be loaded.
social:
  Twitter: https://twitter.com/kemchenj || fab fa-twitter
  Telegram: https://t.me/kemchenj || fab fa-telegram
  E-Mail: mailto:chenkem@gmail.com || fa fa-envelope-o
  Resume: /resume.html || fa fa-address-book-o

links_settings:
  title: 推荐的博客
links:
  iOS 周报: https://github.com/SwiftOldDriver/iOS-Weekly
  iOS Dev Weekly: https://iosdevweekly.com
  Swift Weekly Brief: https://swiftweekly.github.io
  SwiftGG: http://swift.gg/
  喵神博客: https://onevcat.com
  Objective-C 中国: https://objccn.io/issues/

# Sidebar Avatar
avatar:
  # In theme directory (source/images): /images/avatar.gif
  # In site directory (source/uploads): /uploads/avatar.gif
  # You can also use other linking images.
  url: avatar.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: false
  # If true, the avatar would be rotated with the cursor.
  rotated: false

toc:
  expand_all: true

back2top:
  sidebar: true


# ---------------------------------------------------------------
# Post Settings
# See: https://theme-next.org/docs/theme-settings/posts
# ---------------------------------------------------------------

# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: false

# Automatically saving scroll position of each page in the browser.
save_scroll: false

# Automatically excerpt description in homepage as preamble text.
excerpt_description: true


# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

mobile_layout_economy: true

codeblock:
  copy_button:
    enable: true
    style: mac

github_banner:
  enable: true
  permalink: https://github.com/kemchenj
  title: Follow me on GitHub

gitalk:
  enable: true
  github_id: kemchenj # GitHub repo owner
  repo: kemchenj.github.io # Repository name to store issues
  client_id: "ac4cd8966b518e34301a"   # GitHub Application Client ID
  client_secret: "6a8817fe329fc5c4213d860a6b713cd5496d6529"  # GitHub Application Client Secret
  admin_user: kemchenj # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  language: zh-CN

local_search:
  enable: true
  top_n_per_article: 5

motion:
  enable: false

custom_file_path:
  variable: source/_data/variables.styl
