minify: true

favicon:
  small: /favicon-16x16.png
  medium: /favicon-32x32.png
  apple_touch_icon: /apple-icon-180x180.png
  safari_pinned_tab: 

footer:
  since: 2016
  icon:
    name: user
    animated: false
    color: "#808080"
  copyright:

disable_baidu_transformation: true

google_site_verification: aca2a971997c102c

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  about: /about.html || fa fa-user

scheme: Gemini
darkmode: true

social:
  Twitter: https://twitter.com/kemchenj || fab fa-twitter
  Telegram: https://t.me/kemchenj || fab fa-telegram-plane
  E-Mail: mailto:chenkem@gmail.com || fas fa-envelope
  RSS: https://kemchenj.github.io/atom.xml || fas fa-rss

links_settings:
  title: 推荐的博客
links:
  iOS 周报: https://github.com/SwiftOldDriver/iOS-Weekly
  iOS Dev Weekly: https://iosdevweekly.com
  Swift Weekly Brief: https://swiftweekly.github.io
  SwiftGG: http://swift.gg/
  喵神博客: https://onevcat.com
  Objective-C 中国: https://objccn.io/issues/

preconnect: true

avatar:
  url: /images/avatar.jpg

toc:
  number: false
  expand_all: true
  max_depth: 3

back2top:
  sidebar: true
  scrollpercent: true

mobile_layout_economy: true

codeblock:
  prism:
    light: prism
    dark: prism-okaidia
  copy_button:
    enable: true
    style: mac

symbols_count_time:
  separated_meta: false
  item_text_total: true

github_banner:
  enable: true
  permalink: https://github.com/kemchenj/kemchenj.github.io
  title: Source Code

utterances:
  enable: true
  repo: kemchenj/kemchenj.github.io
  # Available values: pathname | url | title | og:title
  issue_term: title
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: preferred-color-scheme

local_search:
  enable: true
  top_n_per_article: 5

motion:
  enable: false

vendors:
  internal: jsdelivr

custom_file_path:
  variable: source/_data/variables.styl
  style: source/_data/styles.styl
